# -*- coding: utf-8 -*-
"""Recognize individual land marks  .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P00Yd2XcRykGuegU_sWOdfHNNz-8hZ51
"""

!pip install pillow

import PIL.Image
import PIL.ImageDraw

!pip install face-recognition

import face_recognition

image = face_recognition.load_image_file("people.jpg")

face_landmarks_list = face_recognition.face_landmarks(image)

number_of_faces = len(face_landmarks_list)
print("I found {} face(s) in this photograph.".format(number_of_faces))

pil_image = PIL.Image.fromarray(image)

draw = PIL.ImageDraw.Draw(pil_image)

for face_landmarks in face_landmarks_list:

    # Loop over each facial feature (eye, nose, mouth, lips, etc)
    for name, list_of_points in face_landmarks.items():

        # Print the location of each facial feature in this image
        print("The {} in this face has the following points: {}".format(name, list_of_points))

        # Let's trace out each facial feature in the image with a line!
        draw.line(list_of_points, fill="red", width=2)

pil_image.show()

pil_image.show()

pil_image.save('image.jpg')

import matplotlib.pyplot as plt
plt.imshow(image)